### ISSUE TITLE
Updating a company fails with AttributeError: 'Resource' object has no attribute 'patch'

### ISSUE THREAD

**Issue by Denniskamau** [googleapis/python-talent#7]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-talent/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-python
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Ubuntu 18.04
  - Python version: ` 3.6.8`
  - pip version: `20.0.2` 
  - `google-cloud-talent` version: ` 0.5.0`

#### Steps to reproduce

  1. Import `build` from `googleapiclient.discovery`
  2. Initialize a client service `client_service = build('jobs', 'v3')`
  3. Update an existing company by calling `patch()`

#### Code example

```
from googleapiclient.discovery import build 
from googleapiclient.errors import Error 

client_service = build('jobs', 'v3')
project_id = 'projects/' + 'PROJECT'
company_name = 'project_id/companies/45df568b-1d6a-46e2-87f8-ca3c59b11830'

def update_company(company_name,company_update,field_mask):
    try:
        request = {'company':company_update, 'updateMask':field_mask}
        result = client_service.projects().patch(
            name=company_name, body=request).execute()
        print('Compnay updated: %s' % result)
        return result
    except Error as e:
        print('Got exception while updating company')
        raise e


```

#### Stack trace
```
result = client_service.projects().patch(
AttributeError: 'Resource' object has no attribute 'patch'

```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
Hi @Denniskamau,

This repository is for the google-cloud-talent library, which is different from the library you appear to be using (google-api-python-client). If possible, you should try to use the more modern google-cloud-talent client.

google-cloud-talent documentation: https://googleapis.dev/python/talent/latest/index.html

If you need to continue using google-api-python-client, there is a large collection of samples [here](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/a9082aa005cb9a0a8d55540dae6e0afab7606d61/jobs/v3).

Thanks!
